image:
  file: .gitpod.Dockerfile

tasks:      
  - name: Workspace Initialization
    env:
      AWS_CLI_AUTO_PROMPT: on-partial

vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - ms-azuretools.vscode-docker
    - ms-python.python
    - hashicorp.terraform
    - redhat.ansible
    - amazonwebservices.aws-toolkit-vscode
