image:
  file: .gitpod.Dockerfile

tasks:      
  - name: Workspace Initialization
    env:
      AWS_CLI_AUTO_PROMPT: on-partial

vscode:
  extensions:
    - ms-python.python
    - hashicorp.terraform
    - amazonwebservices.aws-toolkit-vscode
